#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# ----------------------------- 设置 ------------------------------------------
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    filemanager = "defx"
    filetree_direction = "left"
    vim_help_language = "cn"
    # autocomplete_method = "coc"


# ----------------- SpaceVim 添加的各种 layers ---------------------------------
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
auto_completion_enable_snippets_in_popup = false

[[layers]]
  name = "tags"
  gtagslabel = "ctags"

[[layers]]
  name = "cscope"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 40

[[layers]]
  name = "fzf"

[[layers]]
  name = "colorscheme"
  #random_theme = true

# ----------------- 添加的插件 -------------------------------------------------
[[custom_plugins]]
    name = 'SpaceVim/cscope.vim'
