#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[options]
    filemanager = "defx"
    filetree_direction = "left"
    vim_help_language = "cn"
# ----------------- SpaceVim 添加的各种 layers ---------------------------------

[[layers]]
  name = "chinese"

[[layers]]
  name = "colorscheme"
  #random_theme = true

  
#Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  libclang_path = "/usr/lib/llvm-10/lib/"


#[[layers]]
#  name = "VersionControl"
#  enable-gtm-status = true

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]
    cpp = ["clangd"]

[[layers]]
  name = "format"


# ----------------- 添加的插件 -------------------------------------------------
[[custom_plugins]]
    name = 'junegunn/fzf.vim'

# 以悬浮窗口的形式打开终端
[[custom_plugins]]
    name = 'voldikss/vim-floaterm'

[[custom_plugins]]
  name = 'neovim/nvim-lspconfig'
  merge = 0

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = 0

[[custom_plugins]]
  name = 'simeji/winresizer'

[[custom_plugins]]
  name = 'rhysd/git-messenger.vim'
  lazy =  1
  on_cmd = 'GitMessenger'

[[custom_plugins]]
  name = 'rakr/vim-one'
